# Generated by Django 3.1.1 on 2020-09-11 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 9, 11, 14, 19, 52, 901056, tzinfo=utc)),
        ),
    ]
